name: C/C++ CI

on:
  push:
    branches: [ "master", "develop", "workflow" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: sudo apt-get install -y clang autoconf automake libgc-dev
    - name: update submodules
      run: git submodule update --init --recursive
    - name: build submodules
      run: git submodule foreach ./bootstrap.sh
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: merge develop if current branch is workflow
      run: |
        if [ ${{ github.ref }} == 'refs/heads/workflow' ]; then
          git checkout develop
          git merge workflow
          git push origin develop
        fi
